### ISSUE TITLE
RainbowCakeConfiguration is not configurable in unit tests

### ISSUE THREAD

**Issue by dntks** [rainbowcake/rainbowcake#12]
Hi,

RainbowCakeConfiguration is only configurable from the Application which means the unit tests will have a default consumeExecuteExceptions = true, even if it's set to false in the application, thus I cannot test the exceptions inside the execute() methods.
Any workarounds for this?

**Comment by zsmb13** [comment]
Ah, thanks for raising this, this seems like an oversight on my part. I guess changing configuration in unit tests simply haven't come up yet.

I'll look into providing a proper way to do this.

In the meantime, you could work around by accessing the otherwise `internal` `RainbowCakeConfiguration` object from Java code, or by creating something to call the `rainbowCake` method on. This doesn't have to be a real functioning `Application` instance, it can be a mock or just an `Application` you create by calling its constructor. E.g. `MyApplication().rainbowCake()`

**Comment by zsmb13** [comment]
Finally addressed this in [1.2.0](https://github.com/rainbowcake/rainbowcake/releases/tag/1.2.0-RELEASE)
