### ISSUE TITLE
How to use AsyncLayoutInflator with viewBinding?

### ISSUE THREAD

**Issue by amirzeinaly** [rainbowcake/rainbowcake#29]

**Comment by zsmb13** [comment]
This is out of scope for the library, but I'll address it quickly anyway.

You can `bind` an already inflated layout with DataBinding or ViewBinding ([relevant SO answer](https://stackoverflow.com/a/49516744/4465208)), so you can do that with the layout after creating it async. If you need async inflation in a Fragment, that's another problem to solve, because `onCreateView` has to return something synchronously. For that, you can return an empty container, or something like that ([relevant SO answer](https://stackoverflow.com/a/61035412/4465208)).

With RainbowCake, this could look _something_ like this, though I haven't tested this and don't generally recommend it:

```kotlin
class ViewBindingSampleFragment : RainbowCakeFragment<ViewBindingSampleState, ViewBindingSampleViewModel>() {

    private var _binding: FragmentViewBindingBinding? = null
    private val binding get() = _binding!!

    override fun provideViewModel(): ViewBindingSampleViewModel = getViewModelFromFactory()

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        val context = requireContext()
        return FrameLayout(context)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        AsyncLayoutInflater(view.context)
                .inflate(R.layout.fragment_view_binding, view as ViewGroup) { inflatedView, resid, parent ->
                    parent!!.addView(inflatedView)
                    _binding = FragmentViewBindingBinding.bind(inflatedView)
                }
    }

    ...

}
```

**Comment by amirzeinaly** [comment]
thanks a lot
